ci(default-bare): add workflow_dispatch, permissions, actions/cache, bump actions version, distributions, and java

diff --git a/.github/workflows/default-bare.yml b/.github/workflows/default-bare.yml
--- a/.github/workflows/default-bare.yml
+++ b/.github/workflows/default-bare.yml
@@ -4,32 +4,52 @@ name: default-bare
 on:
   push:
   pull_request:
+  workflow_dispatch:
+
+permissions: {}
 
 jobs:
   build:
-    runs-on: ${{ matrix.os }}
+    permissions:
+      contents: read
+    runs-on: ${{ matrix.distribution }}-${{ matrix.version }}
     continue-on-error: ${{ matrix.experimental }}
     strategy:
       fail-fast: false
       max-parallel: 4
       matrix:
         include:
-          - os: ubuntu-22.04
+          - distribution: ubuntu
+            version: '24.04'
+            suite: default
             experimental: false
-          - os: ubuntu-20.04
+          - distribution: ubuntu
+            version: '22.04'
+            suite: default
             experimental: false
     env:
       ANSIBLE_CALLBACKS_ENABLED: profile_tasks
       ANSIBLE_EXTRA_VARS: ""
+      ANSIBLE_ROLE: kevincoakley.neo4j
+      ANSIBLE_SUITE: ${{ matrix.suite }}
 
     steps:
-      - uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
         with:
-          path: kevincoakley.neo4j
+          path: ${{ env.ANSIBLE_ROLE }}
       - name: Set up Python
-        uses: actions/setup-python@v2
+        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548  # v6.1.0
         with:
           python-version: '3.x'
+      - name: Cache
+        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb  # v5.0.1
+        with:
+          path: |
+            /var/cache/apt/archives
+            /var/lib/apt
+            /var/_install
+          key: cache-ansible-neo4j-${{ steps.get-date.outputs.date }}
       - name: Install dependencies
         run: |
           python3 -m pip install --upgrade pip
@@ -39,8 +59,10 @@ jobs:
           pip3 show ansible
           ls -l $HOME/.local/bin || true
           ansible --version
-          cd $GITHUB_WORKSPACE/kevincoakley.neo4j
-          { echo '[defaults]'; echo 'callbacks_enabled = profile_tasks, timer'; echo 'roles_path = ../'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
+          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE
+          [ -f get-dependencies.sh ] && sh -x get-dependencies.sh
+          [ -f molecule/$ANSIBLE_SUITE/requirements.yml ] && ansible-galaxy install -r molecule/$ANSIBLE_SUITE/requirements.yml
+          { echo '[defaults]'; echo 'callbacks_enabled = profile_tasks, timer'; echo 'roles_path = ../:/home/runner/.ansible/roles'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
       - name: Environment
         run: |
           set -x
@@ -53,23 +75,23 @@ jobs:
           set -x
           sudo rm -Rf /usr/lib/jvm/temurin-8-jdk-amd64 /usr/lib/jvm/temurin-11-jdk-amd64
           sudo update-java-alternatives --list
-          sudo update-java-alternatives -s $(sudo update-java-alternatives -l | grep '17-jdk' | cut -d " " -f1)
+          sudo update-java-alternatives -s $(sudo update-java-alternatives -l | grep '25-jdk' | cut -d " " -f1)
         continue-on-error: true
       - name: Set java - /etc/environment
         run: |
           set -x
           cat /etc/environment
-          sed "s@^JAVA_HOME=/usr/lib/jvm/temurin-11-jdk-amd64@JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64@" /etc/environment | sudo tee /etc/environment
+          sed "s@^JAVA_HOME=/usr/lib/jvm/temurin-11-jdk-amd64@JAVA_HOME=/usr/lib/jvm/temurin-25-jdk-amd64@" /etc/environment | sudo tee /etc/environment
         continue-on-error: true
       - name: run test
         run: |
-          cd $GITHUB_WORKSPACE/kevincoakley.neo4j && ansible-playbook -i localhost, --connection=local --become -vvv molecule/default/playbook.yml ${ANSIBLE_EXTRA_VARS}
+          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/$ANSIBLE_SUITE/playbook.yml ${ANSIBLE_EXTRA_VARS}
         env:
           PY_COLORS: '1'
           ANSIBLE_FORCE_COLOR: '1'
       - name: idempotency run
         run: |
-          cd $GITHUB_WORKSPACE/kevincoakley.neo4j && ansible-playbook -i localhost, --connection=local --become -vvv molecule/default/playbook.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
+          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/$ANSIBLE_SUITE/playbook.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
       - name: On failure
         run: |
           systemctl -l --no-pager status
